### ISSUE TITLE
"sed" breaks binding.gyp on windows

### ISSUE THREAD

**Issue by japj** [lloyd/node-memwatch#17]
On windows (without "sed") the binding.gyp breaks when trying to build node-memwatch:

<pre>
Exception: Call to 'node --version | sed -e "s/^v\([0-9]*\.[0-9]*\).*$/\1/"' returned exit status 255. while trying to load binding.gyp
</pre>

Maybe instead of using sed, you can use the node_version.h macros, like
# if NODE_VERSION_AT_LEAST(0,8,0)
# define NEW_COMPACTION_BEHAVIOR
# endif

**Comment by taichi** [comment]
install [sed for windows](http://gnuwin32.sourceforge.net/packages/sed.htm)

**Comment by lloyd** [comment]
fixed!  thanks @mscdex - please try v0.2.1 on npm now
