### ISSUE TITLE
Ship with pre-built binaries

### ISSUE THREAD

**Issue by scriby** [lloyd/node-memwatch#29]
Some other modules that require a build step (mongodb bson lib, fibers, etc.) ship with pre-built binaries for various platforms. I'm wondering if adding these to npm is something you'd be interested in?

I ask because we brought in the memwatch dependency today and half the dev team couldn't get it built without jumping through some hoops. The other modules have worked seamlessly in terms of "it just works."

Thanks for considering this!

Chris

**Comment by lloyd** [comment]
Interested, but don't know if I'd have the time each release, how do others do this?

-- lloyd (thumb-typing)

**Comment by scriby** [comment]
I asked the author of Fibers what he does. It looks like there is some manual work required with each release.

https://github.com/laverdet/node-fibers/issues/103#issuecomment-14074196

**Comment by lloyd** [comment]
I thought about this, I'm worried it will cause more pain than good.

I'd be very supportive of a fork of memwatch that supplies pre-built binaries on npm??  `memwatch-prebuilt` but cannot commit myself to maintaining it.
