### ISSUE TITLE
Assertion Failed: handle->InternalFieldCount > 0

### ISSUE THREAD

**Issue by dankuck** [lloyd/node-memwatch#30]
node v0.8.18

var hd = new require('memwatch').HeapDiff();

node: /home/ubuntu/.node-gyp/0.8.18/src/node_object_wrap.h:71: void node::ObjectWrap::Wrap(v8::Handlev8::Object): Assertion `handle->InternalFieldCount() > 0' failed.

**Comment by lloyd** [comment]
note - 

```
var hd = new require('memwatch').HeapDiff();
```

doesn't work

```
var hd = new (require('memwatch').HeapDiff)();
```

does.

In any case, the former shouldn't throw an exception, and I'd like to figure out how to make both Just Work.

I'm submitting a fix to make the error clearer, but I'm open to pull requests that make it Just Work.

**Comment by dankuck** [comment]
I had a feeling it was something simple. Thank you.
