### ISSUE TITLE
Is this module still alive?

### ISSUE THREAD

**Issue by goloroden** [lloyd/node-memwatch#61]
Basically, my question is already in the title? Is this module still alive?

Last commit has been in March 2013, 8 open pull requests … it would really be a pity if this project was discontinued.

Any comments on this?

**Comment by ralphtheninja** [comment]
Seems pretty dead yes.

**Comment by franck34** [comment]
perhaps @lloyd is dead too ?

**Comment by MarkHerhold** [comment]
He was last active on Github just 20 days ago.

**Comment by sorenlouv** [comment]
Seems very abandoned to me. Which is a shame, since there are no real alternatives to this (there is [node-heapdump](https://github.com/bnoordhuis/node-heapdump) but it achieves something else).

Perhaps a fork is in order, and get the pull requests rolling?

**Comment by sorenlouv** [comment]
There is already a fork of this project here: https://github.com/marcominetti/node-memwatch

**Comment by jcollum** [comment]
@sqren I got `memwatch-next` to install on OSX with Node 4.4.0. Haven't used it yet but memwatch wouldn't even install. 

This repo seems dead for sure.
