### ISSUE TITLE
Does not support on node.js v.0.12

### ISSUE THREAD

**Issue by smartmouse** [lloyd/node-memwatch#62]
npm WARN package.json querystring@0.2.0 querystring is also the name of a node core module.
/

> memwatch@0.2.2 install /home/bot/test/node_modules/memwatch
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/bot/test/node_modules/memwatch/build'
  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
In file included from ../src/heapdiff.cc:5:
../src/heapdiff.hh:15: error: expected class-name before ‘{’ token
../src/heapdiff.hh:19: error: expected unqualified-id before ‘&’ token
../src/heapdiff.hh:19: error: expected ‘)’ before ‘&’ token
../src/heapdiff.hh:19: error: expected ‘;’ before ‘&’ token
../src/heapdiff.hh:20: error: expected unqualified-id before ‘&’ token
../src/heapdiff.hh:20: error: expected ‘)’ before ‘&’ token
../src/heapdiff.hh:20: error: expected ‘;’ before ‘&’ token
../src/heapdiff.cc: In constructor ‘heapdiff::HeapDiff::HeapDiff()’:
../src/heapdiff.cc:30: error: class ‘heapdiff::HeapDiff’ does not have any field named ‘ObjectWrap’
/home/bot/.node-gyp/0.12.0/deps/v8/include/v8.h: In static member function ‘static void heapdiff::HeapDiff::Initialize(v8::Handle<v8::Object>)’:
/home/bot/.node-gyp/0.12.0/deps/v8/include/v8.h:816: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/heapdiff.cc:51: error: within this context
../src/heapdiff.cc:52: error: ‘New’ was not declared in this scope
../src/heapdiff.cc:54: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/heapdiff.cc:56: error: ‘End’ was not declared in this scope
../src/heapdiff.cc:58: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/heapdiff.cc: At global scope:
../src/heapdiff.cc:62: error: expected unqualified-id before ‘&’ token
../src/heapdiff.cc:62: error: expected ‘)’ before ‘&’ token
../src/heapdiff.cc:62: error: expected initializer before ‘&’ token
../src/heapdiff.cc:23: warning: ‘s_startTime’ defined but not used
make: *** [Release/obj.target/memwatch/src/heapdiff.o] Error 1
make: Leaving directory`/home/bot/test/node_modules/memwatch/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodebot/IBMSVT32/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:268:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 2.6.32-504.el6.ppc64
gyp ERR! command "node" "/home/nodebot/IBMSVT32/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bot/test/node_modules/memwatch
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 2.6.32-504.el6.ppc64
npm ERR! argv "/home/bot/T32/bin/node" "/home/bot/32/bin/npm" "install" "memwatch"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! memwatch@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memwatch@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

**Comment by nmccready** [comment]
+1 needs c, c++ updates fun times

**Comment by francisdb** [comment]
see also https://github.com/lloyd/node-memwatch/issues/59

**Comment by joaomlneto** [comment]
Exactly same problem here. Only difference is I am on 'Linux 3.2.0-4-amd64'. :)

**Comment by jeffreydwalter** [comment]
Same problem on FreeBSD 10.0 with Node v0.12.0.

**Comment by dbellavista** [comment]
+1

**Comment by murali4u45** [comment]
+1

**Comment by HolgerFrank** [comment]
+1

**Comment by imrefazekas** [comment]
+1

**Comment by jodagm** [comment]
+1

**Comment by onury** [comment]
+1

**Comment by nmccready** [comment]
Move on to memwatch-next it works in v0.12.0 and iojs 2

**Comment by onury** [comment]
just did. thanks.

**Comment by cades** [comment]
+1

**Comment by AnushaVenkat** [comment]
Check your node version. Make is not updated for latest node version. 
You can revert node back to 0.10.* & it will work.
to revert back, One way is to use NVM, the Node Version Manager. You can find it at https://github.com/creationix/nvm

It allows you to easily install and manage multiple versions of node. Here's a snippet from the help:

Usage:
nvm install 0.10.31       Download and install a <version>
nvm use 0.10.31           Modify PATH to use <version>
nvm ls                      List versions (installed versions are blue)

**Comment by woss** [comment]
+1

**Comment by harishvadali** [comment]
+1

**Comment by ded** [comment]
so this module is useless without a fix. what's going on with this? who maintains this repo?

**Comment by francisdb** [comment]
Just use https://www.npmjs.com/package/memwatch-next

**Comment by margaritis** [comment]
:+1:

**Comment by ghost** [comment]
+1

**Comment by mark-scott** [comment]
+1

**Comment by smartmouse** [comment]
I just found a memwatch-next that will work with 0.1.2 node.js.
I think memwatch-next is the replacement of memwatch for 0.12 node.js
memwatch will only support 0.10.x node.js.

**Comment by pedro-lucas** [comment]
+1

**Comment by roshangade** [comment]
+1

**Comment by ded** [comment]
# 

# ATTENTION ALL THOSE WHO READ UP TO THIS POINT!!!

It does not look like the maintainer is paying attention to this thread, but as it was pointed out, just use [Memwatch-Next](https://www.npmjs.com/package/memwatch-next)

---

**Comment by smartmouse** [comment]
I am closing this one Now, so use memwatch-next now
