### ISSUE TITLE
Support Node.js 4.x

### ISSUE THREAD

**Issue by paulrutter** [lloyd/node-memwatch#69]
On Windows, I cannot build the memwatch package successfully for Node.js 4.1.1.
It did work on Node.js 0.12.x.

Is Node.js 4.x going to be supported in the near future?

**Comment by robertschultz** [comment]
+1 please support 4.x+.

**Comment by alexdohmen** [comment]
+1

**Comment by wonderdogone** [comment]
this one was working with io.js
https://github.com/marcominetti/node-memwatch

**Comment by toddbluhm** [comment]
+1

**Comment by mgoldsborough** [comment]
+1 v4 support would be great.

**Comment by jonatanpedersen** [comment]
+1

**Comment by vinniejames** [comment]
+1

**Comment by bilko2** [comment]
+1

**Comment by junosuarez** [comment]
It looks like there are a number of unmerged PRs on this repo, and it hasn't been republished on npm in 3 years. Is there any indication that @lloyd is interested in maintaining this module?

**Comment by leaves4j** [comment]
+1

**Comment by junosuarez** [comment]
For the sake of @leaves4j and anyone else who finds this thread, there's a fork of this project called [memwatch-next](https://www.npmjs.com/package/memwatch-next) that works great in node 4
