### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by aichholzer** [lloyd/node-memwatch#84]
Is this project dead?
Happy to pick it up @lloyd

**Comment by stephenh** [comment]
@aichholzer please do! Would love to have something like this. (Maybe it still works? Last commit is in 2013 so I generally assume node/v8 has had a ton of breaking changes since then.)

**Comment by aichholzer** [comment]
I have forked this and will be spinning up a new/updated version of it soon.
https://github.com/aichholzer/node-memwatch
